### ISSUE TITLE
JSON Output : Change single quote to double quote

### ISSUE THREAD

**Issue by MrSunshyne** [Abdur-rahmaanJ/meteomoris#12]
I noticed that my editor complains that the output is not valid json due to the use of single quote. 
I'm not sure if this is different for python projects. 

Please consider changing to Double Quotes if possible.

![image](https://user-images.githubusercontent.com/1721611/157825881-30fd28fa-f38e-4325-931f-4c835430572b.png)

**Comment by Abdur-rahmaanJ** [comment]
@MrSunshyne 

Normally you should do:

```python
import json
with open(latest_file_name, 'w+', encoding='utf8') as f:
    json.dump(result, f, ensure_ascii=False)
````
