### ISSUE TITLE
Add function to scrape main message

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/meteomoris#2]
![meteomoris_mainmessage](https://user-images.githubusercontent.com/22630684/71893582-84576780-3165-11ea-8a0c-7feb0180f58d.png)

**Comment by Abdur-rahmaanJ** [comment]
http://metservice.intnet.mu/

**Comment by rahmadsubakti** [comment]
Can i take this issue?

**Comment by Abdur-rahmaanJ** [comment]
@rahmadsubakti yes, exactly!

**Comment by Abdur-rahmaanJ** [comment]
Solved!
