### ISSUE TITLE
add function to scrape eclipse

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/meteomoris#4]
[http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php](http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php)

![meteomoris_eclipse](https://user-images.githubusercontent.com/22630684/71894112-cfbe4580-3166-11ea-9ff0-c8fdcb4e3604.png)

get the surrounded text till end as string

**Comment by sachingoyal2910** [comment]
I would like to work on this. Can i get some details on this please.

**Comment by Abdur-rahmaanJ** [comment]
@sachingoyal2910 go to the url above, then in meteo.py add a function that fetches the text using beautifulsoup

**Comment by mokrunka** [comment]
If @sachingoyal2910 needs some help, I'd also like to do this.  I think I have a solution, but I need someone to check it.  This is my first time helping on a github project, so I need some help figuring that out too.

**Comment by siddn** [comment]
Hi, if this issue is still open to work on, I would like to contribute if possible, this is my first time helping on a project on github as well

**Comment by debsdo** [comment]
Hey I would like to work on this issue. Can you please assign me?

**Comment by Abdur-rahmaanJ** [comment]
Just PR guys ^^_ mail me arj.python@gmail.com for if you are stuck
